'use strict';
const { randomBytes } = require('crypto');
const { whitespaceScript, whitespaceStyles } = require('./visibleCharacters');
const { iconStyles } = require('./webviewIcons');

function guidedTranslationHtml(webview, extensionUri) {
    const nonce = randomBytes(16).toString('hex');
    return `<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; font-src ${webview.cspSource}; style-src 'unsafe-inline'; script-src 'nonce-${nonce}';"><title>Guided Translation</title><style>${iconStyles(webview, extensionUri)}
${whitespaceStyles}
.ws-edit{position:relative;margin:8px 0;background:var(--vscode-input-background)}.ws-edit textarea{position:relative;z-index:2;margin:0;line-height:1.4;tab-size:4}.ws-overlay{display:none;position:absolute;inset:0;padding:13px;line-height:1.4;white-space:pre-wrap;overflow-wrap:break-word;tab-size:4;overflow:hidden;pointer-events:none}.ws-content{position:relative}body.show-invisibles .ws-overlay{display:block}body.show-invisibles textarea{color:transparent;caret-color:var(--vscode-input-foreground);background:transparent}textarea::selection{color:var(--vscode-input-foreground);background:var(--vscode-editor-selectionBackground,#264f78)}#showInvisibles{flex-shrink:0;width:32px;height:32px;padding:0;font-family:Georgia,serif;font-size:18px}#showInvisibles[aria-pressed="true"]{background:#0078d4;color:#fff;border-color:#0078d4}#showInvisibles[aria-pressed="true"]:hover{background:#006cbe;border-color:#006cbe}
*{box-sizing:border-box}body{font-family:var(--vscode-font-family);background:var(--vscode-editor-background);color:var(--vscode-editor-foreground);padding:24px;max-width:980px;margin:auto;font-size:var(--vscode-font-size,13px)}h1{font-size:24px}h2{font-size:18px;margin:0 0 12px}h3{font-size:13px;margin:0 0 8px}#context,.source,.saved,.proposal{white-space:pre-wrap;overflow-wrap:anywhere}.muted{color:var(--vscode-descriptionForeground)}#workflows{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px;margin:24px 0}button{font:inherit;color:var(--vscode-button-foreground);background:var(--vscode-button-background);border:1px solid var(--vscode-contrastBorder,transparent);padding:8px 12px;border-radius:3px;cursor:pointer}button.secondary{background:var(--vscode-button-secondaryBackground);color:var(--vscode-button-secondaryForeground)}button:focus-visible,textarea:focus-visible{outline:2px solid var(--vscode-focusBorder);outline-offset:3px}button:disabled{opacity:.55;cursor:default}#workflows button{text-align:left;padding:16px}#workflows strong,#workflows span{display:block}#workflows span{margin-top:8px;font-size:12px}.panel{border:1px solid var(--vscode-panel-border);padding:16px;margin:12px 0;border-radius:4px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.comparison{display:grid;grid-template-columns:1fr 1fr;gap:12px}textarea{width:100%;min-height:116px;resize:vertical;font:inherit;color:var(--vscode-input-foreground);background:var(--vscode-input-background);border:1px solid var(--vscode-input-border,var(--vscode-panel-border));padding:12px;margin:8px 0}label{display:block;font-weight:600}#error,#conflict{color:var(--vscode-editorError-foreground)}#status{min-height:22px}progress{width:100%;height:8px;accent-color:var(--vscode-progressBar-background)}ul{padding-left:20px}.hidden{display:none!important}.source{font-size:16px}.badge{padding:3px 6px;background:var(--vscode-badge-background);color:var(--vscode-badge-foreground);border-radius:3px}#entryId{overflow-wrap:anywhere}.toolbar{display:flex;justify-content:space-between;gap:8px;align-items:center;margin:12px 0}@media(max-width:650px){body{padding:14px}.comparison{grid-template-columns:1fr}}
</style></head><body><h1><span class="codicon" aria-hidden="true">&#xebcf;</span> Guided Translation</h1><p id="context" class="muted">XLIFF wird geladen…</p>
<section id="preparation" class="panel hidden"><h2>Neue Sprache vorbereiten</h2><p>1. Sync prüfen · 2. Vorhandene Übersetzungen vorbereiten · 3. Übersetzen und prüfen</p><p id="prepareStatus"></p><p>Kommentare, passende .lng-Einträge und exakte Glossartreffer werden als Entwürfe übernommen. Vorhandene Entwürfe bleiben erhalten. Hier wird keine AI gestartet.</p><div class="actions"><button id="prepareSync">Diese XLIFF synchronisieren</button><button id="prepareImport" class="secondary">Lokale Übersetzungen vorbereiten</button><button id="prepareContinue">Weiter zur Übersetzung</button><button id="prepareBack" class="secondary">Zur Auswahl</button></div></section><section id="start"><p>Wähle den nächsten Schritt. Der Wizard führt dich Eintrag für Eintrag durch die ausgewählte XLIFF.</p><div id="workflows" aria-label="Übersetzungsworkflows"></div></section>
<section id="flow" class="hidden"><div class="toolbar"><h2 id="workflowTitle"></h2><button id="showInvisibles" class="secondary hidden" title="Versteckte Zeichen in Quelltext und Übersetzung anzeigen" aria-label="Versteckte Zeichen anzeigen" aria-pressed="false">¶</button></div><p id="progressLabel" class="muted" role="status"></p><progress id="progress" value="0" max="1" aria-label="Fortschritt"></progress>
<div id="conflict" class="panel hidden" role="alert">Die XLIFF wurde außerhalb des Wizards geändert. Dein Text bleibt erhalten. Kopiere ihn vor dem Neu laden.<div class="actions"><button id="restart" class="secondary">Lokale Entwürfe verwerfen und neu laden</button></div></div>
<div id="entryNavigation" class="actions hidden"><button id="previousEntry" class="secondary" aria-label="Vorheriger Eintrag" title="Vorheriger Eintrag">←</button><button id="nextEntry" class="secondary" aria-label="Nächster Eintrag" title="Nächster Eintrag">→</button></div><div id="entry" class="hidden"><p id="entryId" class="muted"></p><div class="panel"><h3>Quelltext</h3><div id="source" class="source"></div></div><div class="comparison"><div class="panel"><h3>Aktuelle Übersetzung <span id="stateLabel" class="badge"></span></h3><div id="saved" class="saved"></div></div><div id="proposalPanel" class="panel hidden"><h3>Vorschlag</h3><div id="proposal" class="proposal"></div><p id="proposalOrigin" class="muted"></p><button id="useProposal" class="secondary">Vorschlag einsetzen</button></div></div>
<div class="panel"><label for="translation">Übersetzung bearbeiten</label><div class="ws-edit"><textarea id="translation" spellcheck="true"></textarea><div class="ws-overlay" aria-hidden="true"><div id="wsContent" class="ws-content"></div></div></div><p class="muted">Übernehmen ändert die geöffnete XLIFF. Speichern schreibt sie auf den Datenträger. Unübernommene Entwürfe bitte vor dem Schließen speichern.</p><div class="actions"><button id="apply">Übernehmen &amp; weiter</button><button id="skip" class="secondary">Überspringen</button><button id="ai" class="secondary">AI-Vorschlag</button></div></div>
<div id="notesPanel" class="panel hidden"><h3>Entwicklerhinweise</h3><div id="notes"></div></div><div id="glossaryPanel" class="panel hidden"><h3>Glossar</h3><ul id="glossary"></ul></div><div id="qualityPanel" class="panel hidden"><h3>Qualitätshinweise</h3><ul id="quality"></ul></div></div>
<div id="complete" class="panel hidden"><h2>Einträge durchgesehen</h2><p>Speichere deine Änderungen und starte den abschließenden Quality Check. Übersprungene Einträge bleiben offen.</p></div>
<div id="summary" class="panel hidden"><h2>Abschluss</h2><p id="summaryText"></p><p id="qualitySummary"></p><div class="actions"><button id="followMissing" class="secondary">Fehlende ergänzen</button><button id="followSkipped" class="secondary">Übersprungene prüfen</button><button id="followReview" class="secondary">Review starten</button><button id="fixQuality" class="secondary">Qualitätsprobleme beheben</button></div></div>
<div class="actions"><button id="save" class="secondary">Speichern</button><button id="finish">Speichern &amp; Quality Check</button><button id="back" class="secondary">Zur Auswahl</button></div></section>
<div class="actions"><button id="editor" class="secondary" aria-label="Ausgewählte XLIFF im Expert Editor öffnen"><span class="codicon" aria-hidden="true">&#xea73;</span> XLIFF Editor öffnen</button></div><p id="error" role="alert"></p><p id="status" class="muted" role="status" aria-live="polite"></p>
<script nonce="${nonce}">
${whitespaceScript}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const vscode=acquireVsCodeApi();let showInvisibles=Boolean(vscode.getState&&vscode.getState()?.showInvisibles);
function renderCharacters(){for(const id of ['source','saved','proposal','notes']){const el=document.getElementById(id);const value=el.dataset.raw??el.textContent;el.dataset.raw=value;if(showInvisibles)el.innerHTML=whitespaceDecoratedHtml(value);else el.textContent=value;}const editor=document.getElementById('translation');document.getElementById('wsContent').innerHTML=whitespaceDecoratedHtml(editor.value);document.getElementById('wsContent').style.transform='translate('+(-editor.scrollLeft)+'px,'+(-editor.scrollTop)+'px)';document.body.classList.toggle('show-invisibles',showInvisibles);document.getElementById('showInvisibles').setAttribute('aria-pressed',String(showInvisibles));document.getElementById('showInvisibles').title=showInvisibles?'Versteckte Zeichen ausblenden':'Versteckte Zeichen in Quelltext und Übersetzung anzeigen';document.getElementById('showInvisibles').setAttribute('aria-label',showInvisibles?'Versteckte Zeichen ausblenden':'Versteckte Zeichen anzeigen');}
let menu,flow,busy=false,editing=false,localChanged=false,prepareSyncNeeded=false;const $=id=>document.getElementById(id);const titles={'new-language':'Neue Sprache übersetzen','translate-missing':'Fehlende Übersetzungen ergänzen',review:'Übersetzungen überprüfen','quality-fix':'Qualitätsprobleme beheben',skipped:'Übersprungene prüfen'};
function visible(id,show){$(id).classList.toggle('hidden',!show);}function list(id,values){$(id).replaceChildren();for(const value of values){const item=document.createElement('li');item.textContent=value;$(id).append(item);}}
function send(message){busy=true;$('error').textContent='';$('status').textContent=message.action==='ai'?'AI-Vorschlag wird erstellt…':'Wird verarbeitet…';updateControls();vscode.postMessage(message);}
function action(action,text){send({type:'guidedAction',action,revision:flow.revision,...(text===undefined?{}:{text})});}
function editValue(row){const draft=row.localDraft;return draft&&draft.kind==='draft'?draft.translation:row.hasTranslationDraft?row.translationDraft:row.translation||'';}
function updateControls(){$('prepareSync').disabled=busy||!prepareSyncNeeded;const conflict=flow&&flow.conflict;for(const id of ['apply','skip','ai','useProposal','save','finish','back','editor','prepareImport','prepareContinue','prepareBack'])$(id).disabled=busy||Boolean(conflict&&id!=='editor');$('translation').disabled=busy||Boolean(conflict);$('restart').disabled=busy;$('apply').disabled=busy||Boolean(conflict)||!$('translation').value.trim()||Boolean(flow&&flow.workflow==='quality-fix'&&flow.row&&!flow.row.hasTranslationDraft&&$('translation').value===flow.row.translation);$('back').disabled=busy||Boolean(conflict);$('back').title='Eingaben als Entwurf erhalten und zur Auswahl wechseln';$('previousEntry').disabled=busy||Boolean(conflict)||!flow||!flow.canPrevious;$('nextEntry').disabled=busy||Boolean(conflict)||!flow||!flow.canNext;for(const button of $('workflows').querySelectorAll('button'))button.disabled=busy||button.dataset.enabled!=='true';}
function renderMenu(){if(!menu)return;$('context').textContent=menu.file.sourceLanguage+' → '+menu.file.targetLanguage+' · '+menu.file.relativePath;$('workflows').replaceChildren();for(const workflow of menu.workflows){const button=document.createElement('button');button.dataset.enabled=String(workflow.enabled);button.setAttribute('aria-label',workflow.title);button.title=workflow.enabled?workflow.description:'Derzeit nicht erforderlich oder verfügbar';const title=document.createElement('strong');title.textContent=workflow.title;const description=document.createElement('span');description.textContent=workflow.description+(!workflow.enabled?' · Derzeit nicht erforderlich oder verfügbar':'');button.append(title,description);button.addEventListener('click',()=>send({type:'selectWorkflow',workflow:workflow.id}));$('workflows').append(button);}updateControls();}
function renderFlow(next){visible('entryNavigation',next.phase==='entry'||next.phase==='complete');visible('showInvisibles',next.phase==='entry'&&Boolean(next.row));visible('preparation',false);for(const id of ['source','saved','proposal','notes'])delete $(id).dataset.raw;const changed=!flow||!next.row||!flow.row||next.revision!==flow.revision||next.row.ordinal!==flow.row.ordinal;flow=next;busy=Boolean(next.busy);visible('start',false);visible('flow',true);visible('entry',next.phase==='entry'&&Boolean(next.row));visible('complete',next.phase==='complete');visible('summary',next.phase==='summary');visible('conflict',next.conflict);$('workflowTitle').textContent=titles[next.workflow]||'Übersetzung';$('progressLabel').textContent=next.visited+' / '+next.total+' durchgesehen · '+next.accepted+' übernommen · '+next.skipped+' übersprungen';$('progress').max=Math.max(1,next.total);$('progress').value=next.visited;$('error').textContent=next.error||'';
if(next.row){const row=next.row;$('entryId').textContent='Eintrag '+(next.position+1)+' von '+next.total+' · '+row.id;$('source').textContent=row.source;$('saved').textContent=row.translation||'Noch keine Übersetzung';$('stateLabel').textContent=row.rawState||'Ohne Status';if(changed||!next.busy&&!editing&&!localChanged&&!next.error&&!next.conflict){$('translation').value=editValue(row);localChanged=false;}visible('proposalPanel',Boolean(row.proposal));$('proposal').textContent=row.proposal||'';$('proposalOrigin').textContent=row.proposalOrigin||'';const notes=(row.notes||[]).map(note=>[note.from,note.text].filter(Boolean).join(': '));$('notes').textContent=notes.join('\\n');$('notes').style.whiteSpace='pre-wrap';visible('notesPanel',notes.length>0);const terms=(row.glossaryTerms||[]).map(term=>term.source+' → '+term.translation);list('glossary',terms);visible('glossaryPanel',terms.length>0);const issues=(row.qualityIssues||[]).map(issue=>issue.code+': '+issue.message);list('quality',issues);visible('qualityPanel',issues.length>0);}
const q=next.quality&&next.quality.summary;$('summaryText').textContent=next.accepted+' übernommen, '+next.skipped+' übersprungen, '+Math.max(0,next.total-next.visited)+' noch nicht durchgesehen. Änderungen gespeichert; übersprungene Entwürfe bleiben als Entwürfe erhalten.';$('qualitySummary').textContent=q?'Quality Check: '+q.total+' Hinweise · '+q.errors+' Fehler · '+q.warnings+' Warnungen':'Quality Check nicht verfügbar.';const counts=next.summary||{};$('summaryText').textContent=next.accepted+' übernommen · '+(counts.missing||0)+' fehlend · '+(counts.skipped||0)+' übersprungen · '+(counts.drafts||0)+' Entwürfe · '+(counts.proposals||0)+' Vorschläge · '+(counts.review||0)+' zur Prüfung · '+(counts.unvisited||0)+' in diesem Ablauf noch nicht angesehen';for(const [id,key] of [['followMissing','missing'],['followSkipped','skipped'],['followReview','review'],['fixQuality','quality']])$(id).disabled=busy||!counts[key];visible('save',next.phase!=='summary');visible('finish',next.phase!=='summary');$('status').textContent=busy?'Wird verarbeitet…':(next.drafts?next.drafts+' unübernommene Entwürfe':'');updateControls();renderCharacters();}
$('showInvisibles').addEventListener('click',()=>{showInvisibles=!showInvisibles;if(vscode.setState)vscode.setState({showInvisibles});renderCharacters();});$('translation').addEventListener('scroll',renderCharacters);$('translation').addEventListener('input',renderCharacters);
for(const [id,action] of [['prepareSync','sync'],['prepareImport','import'],['prepareContinue','continue']])$(id).addEventListener('click',()=>send({type:'prepareLanguage',action}));$('prepareBack').addEventListener('click',()=>send({type:'backToSelection'}));
$('translation').addEventListener('focus',()=>{editing=true;});$('translation').addEventListener('input',()=>{localChanged=true;updateControls();});$('translation').addEventListener('blur',()=>{editing=false;});
$('apply').addEventListener('click',()=>{localChanged=false;action('apply',$('translation').value);});$('skip').addEventListener('click',()=>{if(localChanged){send({type:'guidedAction',action:'skip',revision:flow.revision,text:$('translation').value});localChanged=false;}else action('skip');});$('ai').addEventListener('click',()=>action('ai',localChanged?$('translation').value:undefined));$('useProposal').addEventListener('click',()=>{localChanged=false;action('useProposal');});$('save').addEventListener('click',()=>{localChanged=false;action('save',flow.row?$('translation').value:undefined);});$('finish').addEventListener('click',()=>{localChanged=false;action('finish',flow.row?$('translation').value:undefined);});$('restart').addEventListener('click',()=>{localChanged=false;action('restart');});$('back').addEventListener('click',()=>{const message={type:'backToSelection',revision:flow&&flow.revision,text:flow&&flow.row?$('translation').value:undefined};localChanged=false;send(message);});for(const [id,workflow] of [['followMissing','translate-missing'],['followSkipped','skipped'],['followReview','review'],['fixQuality','quality-fix']])$(id).addEventListener('click',()=>send({type:'followup',workflow}));$('editor').addEventListener('click',()=>{localChanged=false;send({type:'openEditor',revision:flow&&flow.revision,text:flow&&flow.row?$('translation').value:undefined});});for(const [id,actionName] of [['previousEntry','previous'],['nextEntry','next']])$(id).addEventListener('click',()=>{localChanged=false;action(actionName,flow.row?$('translation').value:undefined);});
window.addEventListener('message',event=>{const message=event.data;if(message.type==='state'){menu=message;renderMenu();}else if(message.type==='guidedState'){renderFlow(message);}else if(message.type==='preparation'){flow=undefined;visible('start',false);visible('flow',false);visible('preparation',true);$('prepareStatus').textContent=message.file.syncStatus==='out-of-sync'?'Diese XLIFF ist noch nicht synchronisiert.':'Sync ist aktuell.';prepareSyncNeeded=message.file.syncStatus==='out-of-sync';$('prepareSync').disabled=busy||!prepareSyncNeeded;$('status').textContent='';}else if(message.type==='selection'){visible('preparation',false);flow=undefined;visible('flow',false);visible('start',true);}else if(message.type==='error')$('error').textContent=message.message;else if(message.type==='idle'){busy=false;if(!flow)$('status').textContent='';updateControls();}});renderCharacters();vscode.postMessage({type:'ready'});
</script></body></html>`;
}

module.exports = { guidedTranslationHtml };
