'use strict';
const { t, htmlText, scriptString, uiLanguage } = require('./localization');
const { randomBytes } = require('crypto');
const { whitespaceScript, whitespaceStyles } = require('./visibleCharacters');
const { iconStyles } = require('./webviewIcons');

function guidedTranslationHtml(webview, extensionUri) {
    const nonce = randomBytes(16).toString('hex');
    return `<!DOCTYPE html><html lang="${uiLanguage()}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; font-src ${webview.cspSource}; style-src 'unsafe-inline'; script-src 'nonce-${nonce}';"><title>${htmlText("Guided Translation")}</title><style>${iconStyles(webview, extensionUri)}
${whitespaceStyles}
.ws-edit{position:relative;margin:8px 0;background:var(--vscode-input-background)}.ws-edit textarea{position:relative;z-index:2;margin:0;line-height:1.4;tab-size:4}.ws-overlay{display:none;position:absolute;inset:0;padding:13px;line-height:1.4;white-space:pre-wrap;overflow-wrap:break-word;tab-size:4;overflow:hidden;pointer-events:none}.ws-content{position:relative}body.show-invisibles .ws-overlay{display:block}body.show-invisibles textarea{color:transparent;caret-color:var(--vscode-input-foreground);background:transparent}textarea::selection{color:var(--vscode-input-foreground);background:var(--vscode-editor-selectionBackground,#264f78)}#showInvisibles{flex-shrink:0;width:32px;height:32px;padding:0;font-family:Georgia,serif;font-size:18px}#showInvisibles[aria-pressed="true"]{background:#0078d4;color:#fff;border-color:#0078d4}#showInvisibles[aria-pressed="true"]:hover{background:#006cbe;border-color:#006cbe}
*{box-sizing:border-box}body{font-family:var(--vscode-font-family);background:var(--vscode-editor-background);color:var(--vscode-editor-foreground);padding:24px;max-width:980px;margin:auto;font-size:var(--vscode-font-size,13px)}h1{font-size:24px}h2{font-size:18px;margin:0 0 12px}h3{font-size:13px;margin:0 0 8px}#context,.source,.saved,.proposal{white-space:pre-wrap;overflow-wrap:anywhere}.muted{color:var(--vscode-descriptionForeground)}#workflows{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px;margin:24px 0}button{font:inherit;color:var(--vscode-button-foreground);background:var(--vscode-button-background);border:1px solid var(--vscode-contrastBorder,transparent);padding:8px 12px;border-radius:3px;cursor:pointer}button.secondary{background:var(--vscode-button-secondaryBackground);color:var(--vscode-button-secondaryForeground)}button:focus-visible,textarea:focus-visible{outline:2px solid var(--vscode-focusBorder);outline-offset:3px}button:disabled{opacity:.55;cursor:default}#workflows button{text-align:left;padding:16px}#workflows strong,#workflows span{display:block}#workflows span{margin-top:8px;font-size:12px}.panel{border:1px solid var(--vscode-panel-border);padding:16px;margin:12px 0;border-radius:4px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.comparison{display:grid;grid-template-columns:1fr 1fr;gap:12px}textarea{width:100%;min-height:116px;resize:vertical;font:inherit;color:var(--vscode-input-foreground);background:var(--vscode-input-background);border:1px solid var(--vscode-input-border,var(--vscode-panel-border));padding:12px;margin:8px 0}label{display:block;font-weight:600}#error,#conflict{color:var(--vscode-editorError-foreground)}#status{min-height:22px}progress{width:100%;height:8px;accent-color:var(--vscode-progressBar-background)}ul{padding-left:20px}.hidden{display:none!important}.source{font-size:16px}.badge{padding:3px 6px;background:var(--vscode-badge-background);color:var(--vscode-badge-foreground);border-radius:3px}#entryId{overflow-wrap:anywhere}.toolbar{display:flex;justify-content:space-between;gap:8px;align-items:center;margin:12px 0}@media(max-width:650px){body{padding:14px}.comparison{grid-template-columns:1fr}}
</style></head><body><h1><span class="codicon" aria-hidden="true">&#xebcf;</span> ${htmlText("Guided Translation")}</h1><p id="context" class="muted">${htmlText("Loading XLIFF…")}</p>
<section id="preparation" class="panel hidden"><h2>${htmlText("Prepare a new language")}</h2><p>${htmlText("1. Check sync · 2. Prepare existing translations · 3. Translate and review")}</p><p id="prepareStatus"></p><p>${htmlText("Comments, matching .lng entries and exact glossary matches become drafts. Existing drafts are preserved. AI is not started here.")}</p><div class="actions"><button id="prepareSync">${htmlText("Synchronize this XLIFF")}</button><button id="prepareImport" class="secondary">${htmlText("Prepare local translations")}</button><button id="prepareContinue">${htmlText("Continue translating")}</button><button id="prepareBack" class="secondary">${htmlText("Back to selection")}</button></div></section><section id="start"><p>${htmlText("Choose the next step. The wizard guides you through the selected XLIFF one entry at a time.")}</p><div id="workflows" aria-label="${htmlText("Translation workflows")}"></div></section>
<section id="flow" class="hidden"><div class="toolbar"><h2 id="workflowTitle"></h2><button id="showInvisibles" class="secondary hidden" title="${htmlText("Show invisible characters in source and translation")}" aria-label="${htmlText("Show non-printing characters")}" aria-pressed="false">¶</button></div><p id="progressLabel" class="muted" role="status"></p><progress id="progress" value="0" max="1" aria-label="${htmlText("Completion")}"></progress>
<div id="conflict" class="panel hidden" role="alert">${htmlText("The XLIFF changed outside the wizard. Your text is preserved. Copy it before reloading.")}<div class="actions"><button id="restart" class="secondary">${htmlText("Discard local drafts and reload")}</button></div></div>
<div id="entryNavigation" class="actions hidden"><button id="previousEntry" class="secondary" aria-label="${htmlText("Previous entry")}" title="${htmlText("Previous entry")}">←</button><button id="nextEntry" class="secondary" aria-label="${htmlText("Next entry")}" title="${htmlText("Next entry")}">→</button></div><div id="entry" class="hidden"><p id="entryId" class="muted"></p><div class="panel"><h3>${htmlText("Source")}</h3><div id="source" class="source"></div></div><div class="comparison"><div class="panel"><h3>${htmlText("Current translation")} <span id="stateLabel" class="badge"></span></h3><div id="saved" class="saved"></div></div><div id="proposalPanel" class="panel hidden"><h3>${htmlText("Proposal")}</h3><div id="proposal" class="proposal"></div><p id="proposalOrigin" class="muted"></p><button id="useProposal" class="secondary">${htmlText("Use proposal")}</button></div></div>
<div class="panel"><label for="translation">${htmlText("Edit translation")}</label><div class="ws-edit"><textarea id="translation" spellcheck="true"></textarea><div class="ws-overlay" aria-hidden="true"><div id="wsContent" class="ws-content"></div></div></div><p class="muted">${htmlText("Apply changes the open XLIFF. Save writes it to disk. Save unapplied drafts before closing.")}</p><div class="actions"><button id="apply">${t("Apply &amp; next")}</button><button id="skip" class="secondary">${htmlText("Skip")}</button><button id="ai" class="secondary">${htmlText("AI proposal")}</button></div></div>
<div id="notesPanel" class="panel hidden"><h3>${htmlText("Developer notes")}</h3><div id="notes"></div></div><div id="glossaryPanel" class="panel hidden"><h3>${htmlText("Glossary")}</h3><ul id="glossary"></ul></div><div id="qualityPanel" class="panel hidden"><h3>${htmlText("Quality findings")}</h3><ul id="quality"></ul></div></div>
<div id="complete" class="panel hidden"><h2>${htmlText("Entries reviewed")}</h2><p>${htmlText("Save your changes and run the final quality check. Skipped entries remain open.")}</p></div>
<div id="summary" class="panel hidden"><h2>${htmlText("Summary")}</h2><p id="summaryText"></p><p id="qualitySummary"></p><div class="actions"><button id="followMissing" class="secondary">${htmlText("Complete missing")}</button><button id="followSkipped" class="secondary">${htmlText("Review skipped")}</button><button id="followReview" class="secondary">${htmlText("Start review")}</button><button id="fixQuality" class="secondary">${htmlText("Fix quality issues")}</button></div></div>
<div class="actions"><button id="save" class="secondary">${htmlText("Save")}</button><button id="finish">${t("Save &amp; Quality Check")}</button><button id="back" class="secondary">${htmlText("Back to selection")}</button></div></section>
<div class="actions"><button id="editor" class="secondary" aria-label="${htmlText("Open the selected XLIFF in the Expert Editor")}"><span class="codicon" aria-hidden="true">&#xea73;</span> ${htmlText("Open XLIFF Editor")}</button></div><p id="error" role="alert"></p><p id="status" class="muted" role="status" aria-live="polite"></p>
<script nonce="${nonce}">
${whitespaceScript}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const vscode=acquireVsCodeApi();let showInvisibles=Boolean(vscode.getState&&vscode.getState()?.showInvisibles);
function renderCharacters(){for(const id of ['source','saved','proposal','notes']){const el=document.getElementById(id);const value=el.dataset.raw??el.textContent;el.dataset.raw=value;if(showInvisibles)el.innerHTML=whitespaceDecoratedHtml(value);else el.textContent=value;}const editor=document.getElementById('translation');document.getElementById('wsContent').innerHTML=whitespaceDecoratedHtml(editor.value);document.getElementById('wsContent').style.transform='translate('+(-editor.scrollLeft)+'px,'+(-editor.scrollTop)+'px)';document.body.classList.toggle('show-invisibles',showInvisibles);document.getElementById('showInvisibles').setAttribute('aria-pressed',String(showInvisibles));document.getElementById('showInvisibles').title=showInvisibles?${scriptString("Hide non-printing characters")}:${scriptString("Show invisible characters in source and translation")};document.getElementById('showInvisibles').setAttribute('aria-label',showInvisibles?${scriptString("Hide non-printing characters")}:${scriptString("Show non-printing characters")});}
let menu,flow,busy=false,editing=false,localChanged=false,prepareSyncNeeded=false;const $=id=>document.getElementById(id);const titles={'new-language':${scriptString("Translate a new language")},'translate-missing':${scriptString("Complete missing translations")},review:${scriptString("Review translations")},'quality-fix':${scriptString("Fix quality issues")},skipped:${scriptString("Review skipped")}};
function visible(id,show){$(id).classList.toggle('hidden',!show);}function list(id,values){$(id).replaceChildren();for(const value of values){const item=document.createElement('li');item.textContent=value;$(id).append(item);}}
function send(message){busy=true;$('error').textContent='';$('status').textContent=message.action==='ai'?${scriptString("Creating AI proposal…")}:${scriptString("Working…")};updateControls();vscode.postMessage(message);}
function action(action,text){send({type:'guidedAction',action,revision:flow.revision,...(text===undefined?{}:{text})});}
function editValue(row){const draft=row.localDraft;return draft&&draft.kind==='draft'?draft.translation:row.hasTranslationDraft?row.translationDraft:row.translation||'';}
function updateControls(){$('prepareSync').disabled=busy||!prepareSyncNeeded;const conflict=flow&&flow.conflict;for(const id of ['apply','skip','ai','useProposal','save','finish','back','editor','prepareImport','prepareContinue','prepareBack'])$(id).disabled=busy||Boolean(conflict&&id!=='editor');$('translation').disabled=busy||Boolean(conflict);$('restart').disabled=busy;$('apply').disabled=busy||Boolean(conflict)||!$('translation').value.trim()||Boolean(flow&&flow.workflow==='quality-fix'&&flow.row&&!flow.row.hasTranslationDraft&&$('translation').value===flow.row.translation);$('back').disabled=busy||Boolean(conflict);$('back').title=${scriptString("Keep your input as a draft and return to selection")};$('previousEntry').disabled=busy||Boolean(conflict)||!flow||!flow.canPrevious;$('nextEntry').disabled=busy||Boolean(conflict)||!flow||!flow.canNext;for(const button of $('workflows').querySelectorAll('button'))button.disabled=busy||button.dataset.enabled!=='true';}
function renderMenu(){if(!menu)return;$('context').textContent=menu.file.sourceLanguage+' → '+menu.file.targetLanguage+' · '+menu.file.relativePath;$('workflows').replaceChildren();for(const workflow of menu.workflows){const button=document.createElement('button');button.dataset.enabled=String(workflow.enabled);button.setAttribute('aria-label',workflow.title);button.title=workflow.enabled?workflow.description:${scriptString("Not currently needed or available")};const title=document.createElement('strong');title.textContent=workflow.title;const description=document.createElement('span');description.textContent=workflow.description+(!workflow.enabled?${scriptString(" · Not currently needed or available")}:'');button.append(title,description);button.addEventListener('click',()=>send({type:'selectWorkflow',workflow:workflow.id}));$('workflows').append(button);}updateControls();}
function renderFlow(next){visible('entryNavigation',next.phase==='entry'||next.phase==='complete');visible('showInvisibles',next.phase==='entry'&&Boolean(next.row));visible('preparation',false);for(const id of ['source','saved','proposal','notes'])delete $(id).dataset.raw;const changed=!flow||!next.row||!flow.row||next.revision!==flow.revision||next.row.ordinal!==flow.row.ordinal;flow=next;busy=Boolean(next.busy);visible('start',false);visible('flow',true);visible('entry',next.phase==='entry'&&Boolean(next.row));visible('complete',next.phase==='complete');visible('summary',next.phase==='summary');visible('conflict',next.conflict);$('workflowTitle').textContent=titles[next.workflow]||${scriptString("Translation")};$('progressLabel').textContent=next.visited+' / '+next.total+${scriptString(" reviewed · ")}+next.accepted+${scriptString(" applied · ")}+next.skipped+${scriptString(" skipped")};$('progress').max=Math.max(1,next.total);$('progress').value=next.visited;$('error').textContent=next.error||'';
if(next.row){const row=next.row;$('entryId').textContent=${scriptString("Entry ")}+(next.position+1)+${scriptString(" of ")}+next.total+' · '+row.id;$('source').textContent=row.source;$('saved').textContent=row.translation||${scriptString("No translation yet")};$('stateLabel').textContent=row.rawState||${scriptString("No State")};if(changed||!next.busy&&!editing&&!localChanged&&!next.error&&!next.conflict){$('translation').value=editValue(row);localChanged=false;}visible('proposalPanel',Boolean(row.proposal));$('proposal').textContent=row.proposal||'';$('proposalOrigin').textContent=row.proposalOrigin||'';const notes=(row.notes||[]).map(note=>[note.from==='Developer'?${scriptString("Developer note")}:note.from,note.text].filter(Boolean).join(': '));$('notes').textContent=notes.join('\\n');$('notes').style.whiteSpace='pre-wrap';visible('notesPanel',notes.length>0);const terms=(row.glossaryTerms||[]).map(term=>term.source+' → '+term.translation);list('glossary',terms);visible('glossaryPanel',terms.length>0);const issues=(row.qualityIssues||[]).map(issue=>issue.code+': '+issue.message);list('quality',issues);visible('qualityPanel',issues.length>0);}
const q=next.quality&&next.quality.summary;$('summaryText').textContent=next.accepted+${scriptString(" applied, ")}+next.skipped+${scriptString(" skipped, ")}+Math.max(0,next.total-next.visited)+${scriptString(" not yet reviewed. Changes saved; skipped drafts remain drafts.")};$('qualitySummary').textContent=q?${scriptString("Quality Check: ")}+q.total+${scriptString(" findings · ")}+q.errors+${scriptString(" error · ")}+q.warnings+${scriptString(" warnings")}:${scriptString("Quality Check unavailable.")};const counts=next.summary||{};$('summaryText').textContent=next.accepted+${scriptString(" applied · ")}+(counts.missing||0)+${scriptString(" missing · ")}+(counts.skipped||0)+${scriptString(" skipped · ")}+(counts.drafts||0)+${scriptString(" drafts · ")}+(counts.proposals||0)+${scriptString(" proposals · ")}+(counts.review||0)+${scriptString(" to review · ")}+(counts.unvisited||0)+${scriptString(" not yet seen in this workflow")};for(const [id,key] of [['followMissing','missing'],['followSkipped','skipped'],['followReview','review'],['fixQuality','quality']])$(id).disabled=busy||!counts[key];visible('save',next.phase!=='summary');visible('finish',next.phase!=='summary');$('status').textContent=busy?${scriptString("Working…")}:(next.drafts?next.drafts+${scriptString(" unapplied drafts")}:'');updateControls();renderCharacters();}
$('showInvisibles').addEventListener('click',()=>{showInvisibles=!showInvisibles;if(vscode.setState)vscode.setState({showInvisibles});renderCharacters();});$('translation').addEventListener('scroll',renderCharacters);$('translation').addEventListener('input',renderCharacters);
for(const [id,action] of [['prepareSync','sync'],['prepareImport','import'],['prepareContinue','continue']])$(id).addEventListener('click',()=>send({type:'prepareLanguage',action}));$('prepareBack').addEventListener('click',()=>send({type:'backToSelection'}));
$('translation').addEventListener('focus',()=>{editing=true;});$('translation').addEventListener('input',()=>{localChanged=true;updateControls();});$('translation').addEventListener('blur',()=>{editing=false;});
$('apply').addEventListener('click',()=>{localChanged=false;action('apply',$('translation').value);});$('skip').addEventListener('click',()=>{if(localChanged){send({type:'guidedAction',action:'skip',revision:flow.revision,text:$('translation').value});localChanged=false;}else action('skip');});$('ai').addEventListener('click',()=>action('ai',localChanged?$('translation').value:undefined));$('useProposal').addEventListener('click',()=>{localChanged=false;action('useProposal');});$('save').addEventListener('click',()=>{localChanged=false;action('save',flow.row?$('translation').value:undefined);});$('finish').addEventListener('click',()=>{localChanged=false;action('finish',flow.row?$('translation').value:undefined);});$('restart').addEventListener('click',()=>{localChanged=false;action('restart');});$('back').addEventListener('click',()=>{const message={type:'backToSelection',revision:flow&&flow.revision,text:flow&&flow.row?$('translation').value:undefined};localChanged=false;send(message);});for(const [id,workflow] of [['followMissing','translate-missing'],['followSkipped','skipped'],['followReview','review'],['fixQuality','quality-fix']])$(id).addEventListener('click',()=>send({type:'followup',workflow}));$('editor').addEventListener('click',()=>{localChanged=false;send({type:'openEditor',revision:flow&&flow.revision,text:flow&&flow.row?$('translation').value:undefined});});for(const [id,actionName] of [['previousEntry','previous'],['nextEntry','next']])$(id).addEventListener('click',()=>{localChanged=false;action(actionName,flow.row?$('translation').value:undefined);});
window.addEventListener('message',event=>{const message=event.data;if(message.type==='state'){menu=message;renderMenu();}else if(message.type==='guidedState'){renderFlow(message);}else if(message.type==='preparation'){flow=undefined;visible('start',false);visible('flow',false);visible('preparation',true);$('prepareStatus').textContent=message.file.syncStatus==='out-of-sync'?${scriptString("This XLIFF is not synchronized yet.")}:${scriptString("Sync is up to date.")};prepareSyncNeeded=message.file.syncStatus==='out-of-sync';$('prepareSync').disabled=busy||!prepareSyncNeeded;$('status').textContent='';}else if(message.type==='selection'){visible('preparation',false);flow=undefined;visible('flow',false);visible('start',true);}else if(message.type==='error')$('error').textContent=message.message;else if(message.type==='idle'){busy=false;if(!flow)$('status').textContent='';updateControls();}});renderCharacters();vscode.postMessage({type:'ready'});
</script></body></html>`;
}

module.exports = { guidedTranslationHtml };
